<?php

/**
 * @file
 * HURDAT2 Parser - hook implementations
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function feeds_hurdat2_ctools_plugin_api($owner, $api) {
    if ($owner == 'feeds' && $api == 'plugins') {
        return array('version' => 2);
    }
}

/**
 * Implements hook_feeds_plugins().
 */
function feeds_hurdat2_feeds_plugins() {
    $info = array();
    $info['HURDAT2Parser'] = array(
        'name' => 'HURDAT2 parser',
        'description' => 'Parses a HURDAT2 (c. 2012) file.',
        'help' => 'HURDAT2Parser ...',
        'handler' => array(
            'parent' => 'FeedsParser',
            'class' => 'FeedsHURDAT2Parser',
            'file' => 'HURDAT2Parser.inc',
            'path' => drupal_get_path('module', 'feeds_hurdat2'),
        ),
    );
    return $info;
}
